{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.136.1202.0 (24.09)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Adding Columns\",\"Advanced Splitting\",\"Blank Rows\",\"Null\",\"Pivot\",\"Sheet1\",\"Split & Merge Columns\",\"Transpose\",\"Unpivot\",\"Table\",\"Fact table\",\"DimCustomer\",\"DimEmployee\",\"DimProduct\",\"DimSupplier\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Adding Columns",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Sodiq\\Documents\\Self Dev\\Data_Preprocessing_&_Modelling.xlsx\"), null, true),",
          "    #\"Adding Columns_Sheet\" = Source{[Item=\"Adding Columns\",Kind=\"Sheet\"]}[Data],",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Adding Columns_Sheet\", [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"ProductID\", Int64.Type}, {\"ProductNumber\", type text}, {\"Name\", type text}, {\"Size\", type any}, {\"UnitPrice\", type number}, {\"Sales\", type number}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "661d0a26-62ed-41d6-875c-b32cb4e0fe93"
      },
      {
        "name": "Advanced Splitting",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Sodiq\\Documents\\Self Dev\\Data_Preprocessing_&_Modelling.xlsx\"), null, true),",
          "    #\"Advanced Splitting_Sheet\" = Source{[Item=\"Advanced Splitting\",Kind=\"Sheet\"]}[Data],",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Advanced Splitting_Sheet\", [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"ProductID\", Int64.Type}, {\"ProductNumber\", type text}, {\"Name\", type text}, {\"Size\", type any}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "d978eb34-dc47-49ce-8fb1-b35240e9ce8d"
      },
      {
        "name": "Blank Rows",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Sodiq\\Documents\\Self Dev\\Data_Preprocessing_&_Modelling.xlsx\"), null, true),",
          "    #\"Blank Rows_Sheet\" = Source{[Item=\"Blank Rows\",Kind=\"Sheet\"]}[Data],",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Blank Rows_Sheet\", [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Ship Mode\", type text}, {\"Customer ID\", type any}, {\"Customer Name\", type text}, {\"Segment\", type text}, {\"Sales\", type number}}),",
          "    #\"Removed Blank Rows\" = Table.SelectRows(#\"Changed Type\", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {\"\", null}))),",
          "    #\"Filtered Rows\" = Table.SelectRows(#\"Removed Blank Rows\", each ([Ship Mode] <> null)),",
          "    #\"Removed Bottom Rows\" = Table.RemoveLastN(#\"Filtered Rows\",1)",
          "in",
          "    #\"Removed Bottom Rows\""
        ],
        "kind": "m",
        "lineageTag": "f2e887ed-b17c-4be2-a31e-ae3a01676ab2"
      },
      {
        "name": "Null",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Sodiq\\Documents\\Self Dev\\Data_Preprocessing_&_Modelling.xlsx\"), null, true),",
          "    Null_Sheet = Source{[Item=\"Null\",Kind=\"Sheet\"]}[Data],",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Null_Sheet, [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Name\", type text}, {\"Color\", type text}, {\"Size\", type any}, {\"UnitPrice\", type number}, {\"Sales\", type number}, {\"SellStartDate\", type datetime}, {\"SellEndDate\", type any}, {\"DiscontinuedDate\", type text}, {\"ProductCategory\", type text}}),",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"DiscontinuedDate\"}),",
          "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Removed Columns\",{{\"SellEndDate\", type date}, {\"SellStartDate\", type date}}),",
          "    #\"Added Conditional Column\" = Table.AddColumn(#\"Changed Type1\", \"Custom\", each if [SellEndDate] = null then \"Sales Not end\" else \"Sales Ended\"),",
          "    #\"Filled Down\" = Table.FillDown(#\"Added Conditional Column\",{\"Color\"}),",
          "    #\"Replaced Value\" = Table.ReplaceValue(#\"Filled Down\",\"NULL\",\"No Color\",Replacer.ReplaceText,{\"Color\"})",
          "in",
          "    #\"Replaced Value\""
        ],
        "kind": "m",
        "lineageTag": "0bf28f98-c77c-4212-8e2d-16959e67b959"
      },
      {
        "name": "Pivot",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "expression": [
          "let",
          "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Sodiq\\Documents\\Self Dev\\Data_Preprocessing_&_Modelling.xlsx\"), null, true),",
          "    Pivot_Sheet = Source{[Item=\"Pivot\",Kind=\"Sheet\"]}[Data],",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Pivot_Sheet, [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Product Name\", type text}, {\"ProductCategory\", type text}, {\"Sales\", type number}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "315a7243-fae0-41e4-a336-e6ceea6a8ebd"
      },
      {
        "name": "Sheet1",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "expression": [
          "let",
          "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Sodiq\\Documents\\Self Dev\\Data_Preprocessing_&_Modelling.xlsx\"), null, true),",
          "    Sheet1_Sheet = Source{[Item=\"Sheet1\",Kind=\"Sheet\"]}[Data],",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"ProductID\", Int64.Type}, {\"ProductNumber\", type text}, {\"Name\", type text}, {\"Color\", type text}, {\"Size\", type any}, {\"UnitPrice\", type number}, {\"Sales\", type number}, {\"SellStartDate\", type datetime}, {\"SellEndDate\", type any}, {\"DiscontinuedDate\", type text}, {\"ProductType\", type text}, {\"ProductCategory\", type text}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "9a0b6247-fa03-41b5-8aaf-ab0aaf98520a"
      },
      {
        "name": "Split & Merge Columns",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Sodiq\\Documents\\Self Dev\\Data_Preprocessing_&_Modelling.xlsx\"), null, true),",
          "    #\"Split & Merge Columns_Sheet\" = Source{[Item=\"Split & Merge Columns\",Kind=\"Sheet\"]}[Data],",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Split & Merge Columns_Sheet\", [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"CustomerID\", Int64.Type}, {\"FirstName\", type text}, {\"LastName\", type text}, {\"CompanyName\", type text}, {\"SalesPerson\", type text}}),",
          "    #\"Split Column by Delimiter\" = Table.SplitColumn(#\"Changed Type\", \"SalesPerson\", Splitter.SplitTextByEachDelimiter({\"\\\"}, QuoteStyle.Csv, true), {\"SalesPerson.1\", \"SalesPerson.2\"}),",
          "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Split Column by Delimiter\",{{\"SalesPerson.1\", type text}, {\"SalesPerson.2\", type text}})",
          "in",
          "    #\"Changed Type1\""
        ],
        "kind": "m",
        "lineageTag": "99aaed3e-c7a5-4765-9511-e9b585cefaa7"
      },
      {
        "name": "Transpose",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "expression": [
          "let",
          "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Sodiq\\Documents\\Self Dev\\Data_Preprocessing_&_Modelling.xlsx\"), null, true),",
          "    Transpose_Sheet = Source{[Item=\"Transpose\",Kind=\"Sheet\"]}[Data],",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Transpose_Sheet, [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Product Name\", type text}, {\"HL Road Frame - Black, 58\", type any}, {\"HL Road Frame - Red, 58\", type any}, {\"Sport-100 Helmet, Red\", type any}, {\"Sport-100 Helmet, Black\", type any}, {\"Mountain Bike Socks, M\", type any}, {\"Mountain Bike Socks, L\", type any}, {\"Sport-100 Helmet, Blue\", type any}, {\"AWC Logo Cap\", type any}, {\"Long-Sleeve Logo Jersey, S\", type any}, {\"Long-Sleeve Logo Jersey, M\", type any}, {\"Long-Sleeve Logo Jersey, L\", type any}, {\"Long-Sleeve Logo Jersey, XL\", type any}, {\"HL Road Frame - Red, 62\", type any}, {\"HL Road Frame - Red, 44\", type any}, {\"HL Road Frame - Red, 48\", type any}, {\"HL Road Frame - Red, 52\", type any}, {\"HL Road Frame - Red, 56\", type any}, {\"LL Road Frame - Black, 58\", type any}, {\"LL Road Frame - Black, 60\", type any}, {\"LL Road Frame - Black, 62\", type any}, {\"LL Road Frame - Red, 44\", type any}, {\"LL Road Frame - Red, 48\", type any}, {\"LL Road Frame - Red, 52\", type any}, {\"LL Road Frame - Red, 58\", type any}, {\"LL Road Frame - Red, 60\", type any}, {\"LL Road Frame - Red, 62\", type any}, {\"ML Road Frame - Red, 44\", type any}, {\"ML Road Frame - Red, 48\", type any}, {\"ML Road Frame - Red, 52\", type any}, {\"ML Road Frame - Red, 58\", type any}, {\"ML Road Frame - Red, 60\", type any}, {\"LL Road Frame - Black, 44\", type any}, {\"LL Road Frame - Black, 48\", type any}, {\"LL Road Frame - Black, 52\", type any}, {\"HL Mountain Frame - Silver, 42\", type any}, {\"HL Mountain Frame - Silver, 44\", type any}, {\"HL Mountain Frame - Silver, 48\", type any}, {\"HL Mountain Frame - Silver, 46\", type any}, {\"HL Mountain Frame - Black, 42\", type any}, {\"HL Mountain Frame - Black, 44\", type any}, {\"HL Mountain Frame - Black, 48\", type any}, {\"HL Mountain Frame - Black, 46\", type any}, {\"HL Mountain Frame - Black, 38\", type any}, {\"HL Mountain Frame - Silver, 38\", type any}, {\"Road-150 Red, 62\", type any}, {\"Road-150 Red, 44\", type any}, {\"Road-150 Red, 48\", type any}, {\"Road-150 Red, 52\", type any}, {\"Road-150 Red, 56\", type any}, {\"Road-450 Red, 58\", type any}, {\"Road-450 Red, 60\", type any}, {\"Road-450 Red, 44\", type any}, {\"Road-450 Red, 48\", type any}, {\"Road-450 Red, 52\", type any}, {\"Road-650 Red, 58\", type any}, {\"Road-650 Red, 60\", type any}, {\"Road-650 Red, 62\", type any}, {\"Road-650 Red, 44\", type any}, {\"Road-650 Red, 48\", type any}, {\"Road-650 Red, 52\", type any}, {\"Road-650 Black, 58\", type any}, {\"Road-650 Black, 60\", type any}, {\"Road-650 Black, 62\", type any}, {\"Road-650 Black, 44\", type any}, {\"Road-650 Black, 48\", type any}, {\"Road-650 Black, 52\", type any}, {\"Mountain-100 Silver, 38\", type any}, {\"Mountain-100 Silver, 42\", type any}, {\"Mountain-100 Silver, 44\", type any}, {\"Mountain-100 Silver, 48\", type any}, {\"Mountain-100 Black, 38\", type any}, {\"Mountain-100 Black, 42\", type any}, {\"Mountain-100 Black, 44\", type any}, {\"Mountain-100 Black, 48\", type any}, {\"Mountain-200 Silver, 38\", type any}, {\"Mountain-200 Silver, 42\", type any}, {\"Mountain-200 Silver, 46\", type any}, {\"Mountain-200 Black, 38\", type any}, {\"Mountain-200 Black, 42\", type any}, {\"Mountain-200 Black, 46\", type any}, {\"Mountain-300 Black, 38\", type any}, {\"Mountain-300 Black, 40\", type any}, {\"Mountain-300 Black, 44\", type any}, {\"Mountain-300 Black, 48\", type any}, {\"Road-250 Red, 44\", type any}, {\"Road-250 Red, 48\", type any}, {\"Road-250 Red, 52\", type any}, {\"Road-250 Red, 58\", type any}, {\"Road-250 Black, 44\", type any}, {\"Road-250 Black, 48\", type any}, {\"Road-250 Black, 52\", type any}, {\"Road-250 Black, 58\", type any}, {\"Road-550-W Yellow, 38\", type any}, {\"Road-550-W Yellow, 40\", type any}, {\"Road-550-W Yellow, 42\", type any}, {\"Road-550-W Yellow, 44\", type any}, {\"Road-550-W Yellow, 48\", type any}, {\"LL Fork\", type any}, {\"ML Fork\", type any}, {\"HL Fork\", type any}, {\"LL Headset\", type any}, {\"ML Headset\", type any}, {\"HL Headset\", type any}, {\"LL Mountain Handlebars\", type any}, {\"ML Mountain Handlebars\", type any}, {\"HL Mountain Handlebars\", type any}, {\"LL Road Handlebars\", type any}, {\"ML Road Handlebars\", type any}, {\"HL Road Handlebars\", type any}, {\"ML Mountain Frame - Black, 38\", type any}, {\"LL Mountain Front Wheel\", type any}, {\"ML Mountain Front Wheel\", type any}, {\"HL Mountain Front Wheel\", type any}, {\"LL Road Front Wheel\", type any}, {\"ML Road Front Wheel\", type any}, {\"HL Road Front Wheel\", type any}, {\"Touring Front Wheel\", type any}, {\"ML Road Frame-W - Yellow, 38\", type any}, {\"LL Mountain Rear Wheel\", type any}, {\"ML Mountain Rear Wheel\", type any}, {\"HL Mountain Rear Wheel\", type any}, {\"LL Road Rear Wheel\", type any}, {\"ML Road Rear Wheel\", type any}, {\"HL Road Rear Wheel\", type any}, {\"Touring Rear Wheel\", type any}, {\"ML Mountain Frame - Black, 40\", type any}, {\"ML Mountain Frame - Black, 44\", type any}, {\"ML Mountain Frame - Black, 48\", type any}, {\"ML Road Frame-W - Yellow, 40\", type any}, {\"ML Road Frame-W - Yellow, 42\", type any}, {\"ML Road Frame-W - Yellow, 44\", type any}, {\"ML Road Frame-W - Yellow, 48\", type any}, {\"HL Road Frame - Black, 62\", type any}, {\"HL Road Frame - Black, 44\", type any}, {\"HL Road Frame - Black, 48\", type any}, {\"HL Road Frame - Black, 52\", type any}, {\"Men's Sports Shorts, S\", type any}, {\"Touring-Panniers, Large\", type any}, {\"Cable Lock\", type any}, {\"Minipump\", type any}, {\"Mountain Pump\", type any}, {\"Taillights - Battery-Powered\", type any}, {\"Headlights - Dual-Beam\", type any}, {\"Headlights - Weatherproof\", type any}, {\"Men's Sports Shorts, M\", type any}, {\"Men's Sports Shorts, L\", type any}, {\"Men's Sports Shorts, XL\", type any}, {\"Women's Tights, S\", type any}, {\"Women's Tights, M\", type any}, {\"Women's Tights, L\", type any}, {\"Men's Bib-Shorts, S\", type any}, {\"Men's Bib-Shorts, M\", type any}, {\"Men's Bib-Shorts, L\", type any}, {\"Half-Finger Gloves, S\", type any}, {\"Half-Finger Gloves, M\", type any}, {\"Half-Finger Gloves, L\", type any}, {\"Full-Finger Gloves, S\", type any}, {\"Full-Finger Gloves, M\", type any}, {\"Full-Finger Gloves, L\", type any}, {\"Classic Vest, S\", type any}, {\"Classic Vest, M\", type any}, {\"Classic Vest, L\", type any}, {\"Women's Mountain Shorts, S\", type any}, {\"Women's Mountain Shorts, M\", type any}, {\"Women's Mountain Shorts, L\", type any}, {\"Water Bottle - 30 oz.\", type any}, {\"Mountain Bottle Cage\", type any}, {\"Road Bottle Cage\", type any}, {\"Patch Kit/8 Patches\", type any}, {\"Racing Socks, M\", type any}, {\"Racing Socks, L\", type any}, {\"Hitch Rack - 4-Bike\", type any}, {\"Bike Wash - Dissolver\", type any}, {\"Fender Set - Mountain\", type any}, {\"All-Purpose Bike Stand\", type any}, {\"Hydration Pack - 70 oz.\", type any}, {\"Short-Sleeve Classic Jersey, S\", type any}, {\"Short-Sleeve Classic Jersey, M\", type any}, {\"Short-Sleeve Classic Jersey, L\", type any}, {\"Short-Sleeve Classic Jersey, XL\", type any}, {\"HL Touring Frame - Yellow, 60\", type any}, {\"LL Touring Frame - Yellow, 62\", type any}, {\"HL Touring Frame - Yellow, 46\", type any}, {\"HL Touring Frame - Yellow, 50\", type any}, {\"HL Touring Frame - Yellow, 54\", type any}, {\"HL Touring Frame - Blue, 46\", type any}, {\"HL Touring Frame - Blue, 50\", type any}, {\"HL Touring Frame - Blue, 54\", type any}, {\"HL Touring Frame - Blue, 60\", type any}, {\"Rear Derailleur\", type any}, {\"LL Touring Frame - Blue, 50\", type any}, {\"LL Touring Frame - Blue, 54\", type any}, {\"LL Touring Frame - Blue, 58\", type any}, {\"LL Touring Frame - Blue, 62\", type any}, {\"LL Touring Frame - Yellow, 44\", type any}, {\"LL Touring Frame - Yellow, 50\", type any}, {\"LL Touring Frame - Yellow, 54\", type any}, {\"LL Touring Frame - Yellow, 58\", type any}, {\"LL Touring Frame - Blue, 44\", type any}, {\"ML Mountain Frame-W - Silver, 40\", type any}, {\"ML Mountain Frame-W - Silver, 42\", type any}, {\"ML Mountain Frame-W - Silver, 46\", type any}, {\"Rear Brakes\", type any}, {\"LL Mountain Seat/Saddle\", type any}, {\"ML Mountain Seat/Saddle\", type any}, {\"HL Mountain Seat/Saddle\", type any}, {\"LL Road Seat/Saddle\", type any}, {\"ML Road Seat/Saddle\", type any}, {\"HL Road Seat/Saddle\", type any}, {\"LL Touring Seat/Saddle\", type any}, {\"ML Touring Seat/Saddle\", type any}, {\"HL Touring Seat/Saddle\", type any}, {\"LL Mountain Frame - Silver, 42\", type any}, {\"LL Mountain Frame - Silver, 44\", type any}, {\"LL Mountain Frame - Silver, 48\", type any}, {\"LL Mountain Frame - Silver, 52\", type any}, {\"Mountain Tire Tube\", type any}, {\"Road Tire Tube\", type any}, {\"Touring Tire Tube\", type any}, {\"LL Mountain Frame - Black, 42\", type any}, {\"LL Mountain Frame - Black, 44\", type any}, {\"LL Mountain Frame - Black, 48\", type any}, {\"LL Mountain Frame - Black, 52\", type any}, {\"LL Mountain Tire\", type any}, {\"ML Mountain Tire\", type any}, {\"HL Mountain Tire\", type any}, {\"LL Road Tire\", type any}, {\"ML Road Tire\", type any}, {\"HL Road Tire\", type any}, {\"Touring Tire\", type any}, {\"LL Mountain Pedal\", type any}, {\"ML Mountain Pedal\", type any}, {\"HL Mountain Pedal\", type any}, {\"LL Road Pedal\", type any}, {\"ML Road Pedal\", type any}, {\"HL Road Pedal\", type any}, {\"Touring Pedal\", type any}, {\"ML Mountain Frame-W - Silver, 38\", type any}, {\"LL Mountain Frame - Black, 40\", type any}, {\"LL Mountain Frame - Silver, 40\", type any}, {\"Front Derailleur\", type any}, {\"LL Touring Handlebars\", type any}, {\"HL Touring Handlebars\", type any}, {\"Front Brakes\", type any}, {\"LL Crankset\", type any}, {\"ML Crankset\", type any}, {\"HL Crankset\", type any}, {\"Chain\", type any}, {\"Touring-2000 Blue, 60\", type any}, {\"Touring-1000 Yellow, 46\", type any}, {\"Touring-1000 Yellow, 50\", type any}, {\"Touring-1000 Yellow, 54\", type any}, {\"Touring-1000 Yellow, 60\", type any}, {\"Touring-3000 Blue, 54\", type any}, {\"Touring-3000 Blue, 58\", type any}, {\"Touring-3000 Blue, 62\", type any}, {\"Touring-3000 Yellow, 44\", type any}, {\"Touring-3000 Yellow, 50\", type any}, {\"Touring-3000 Yellow, 54\", type any}, {\"Touring-3000 Yellow, 58\", type any}, {\"Touring-3000 Yellow, 62\", type any}, {\"Touring-1000 Blue, 46\", type any}, {\"Touring-1000 Blue, 50\", type any}, {\"Touring-1000 Blue, 54\", type any}, {\"Touring-1000 Blue, 60\", type any}, {\"Touring-2000 Blue, 46\", type any}, {\"Touring-2000 Blue, 50\", type any}, {\"Touring-2000 Blue, 54\", type any}, {\"Road-350-W Yellow, 40\", type any}, {\"Road-350-W Yellow, 42\", type any}, {\"Road-350-W Yellow, 44\", type any}, {\"Road-350-W Yellow, 48\", type any}, {\"Road-750 Black, 58\", type any}, {\"Touring-3000 Blue, 44\", type any}, {\"Touring-3000 Blue, 50\", type any}, {\"Mountain-400-W Silver, 38\", type any}, {\"Mountain-400-W Silver, 40\", type any}, {\"Mountain-400-W Silver, 42\", type any}, {\"Mountain-400-W Silver, 46\", type any}, {\"Mountain-500 Silver, 40\", type any}, {\"Mountain-500 Silver, 42\", type any}, {\"Mountain-500 Silver, 44\", type any}, {\"Mountain-500 Silver, 48\", type any}, {\"Mountain-500 Silver, 52\", type any}, {\"Mountain-500 Black, 40\", type any}, {\"Mountain-500 Black, 42\", type any}, {\"Mountain-500 Black, 44\", type any}, {\"Mountain-500 Black, 48\", type any}, {\"Mountain-500 Black, 52\", type any}, {\"LL Bottom Bracket\", type any}, {\"ML Bottom Bracket\", type any}, {\"HL Bottom Bracket\", type any}, {\"Road-750 Black, 44\", type any}, {\"Road-750 Black, 48\", type any}, {\"Road-750 Black, 52\", type any}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "56b5fd93-6199-4c25-b072-ecf28d67a8e3"
      },
      {
        "name": "Unpivot",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Sodiq\\Documents\\Self Dev\\Data_Preprocessing_&_Modelling.xlsx\"), null, true),",
          "    Unpivot_Sheet = Source{[Item=\"Unpivot\",Kind=\"Sheet\"]}[Data],",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Unpivot_Sheet, [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Product Name\", type text}, {\"HL Road Frame - Black, 58\", type any}, {\"HL Road Frame - Red, 58\", type any}, {\"Sport-100 Helmet, Red\", type any}, {\"Sport-100 Helmet, Black\", type any}, {\"Mountain Bike Socks, M\", type any}, {\"Mountain Bike Socks, L\", type any}, {\"Sport-100 Helmet, Blue\", type any}, {\"AWC Logo Cap\", type any}, {\"Long-Sleeve Logo Jersey, S\", type any}, {\"Long-Sleeve Logo Jersey, M\", type any}, {\"Long-Sleeve Logo Jersey, L\", type any}, {\"Long-Sleeve Logo Jersey, XL\", type any}, {\"HL Road Frame - Red, 62\", type any}, {\"HL Road Frame - Red, 44\", type any}, {\"HL Road Frame - Red, 48\", type any}, {\"HL Road Frame - Red, 52\", type any}, {\"HL Road Frame - Red, 56\", type any}, {\"LL Road Frame - Black, 58\", type any}, {\"LL Road Frame - Black, 60\", type any}, {\"LL Road Frame - Black, 62\", type any}, {\"LL Road Frame - Red, 44\", type any}, {\"LL Road Frame - Red, 48\", type any}, {\"LL Road Frame - Red, 52\", type any}, {\"LL Road Frame - Red, 58\", type any}, {\"LL Road Frame - Red, 60\", type any}, {\"LL Road Frame - Red, 62\", type any}, {\"ML Road Frame - Red, 44\", type any}, {\"ML Road Frame - Red, 48\", type any}, {\"ML Road Frame - Red, 52\", type any}, {\"ML Road Frame - Red, 58\", type any}, {\"ML Road Frame - Red, 60\", type any}, {\"LL Road Frame - Black, 44\", type any}, {\"LL Road Frame - Black, 48\", type any}, {\"LL Road Frame - Black, 52\", type any}, {\"HL Mountain Frame - Silver, 42\", type any}, {\"HL Mountain Frame - Silver, 44\", type any}, {\"HL Mountain Frame - Silver, 48\", type any}, {\"HL Mountain Frame - Silver, 46\", type any}, {\"HL Mountain Frame - Black, 42\", type any}, {\"HL Mountain Frame - Black, 44\", type any}, {\"HL Mountain Frame - Black, 48\", type any}, {\"HL Mountain Frame - Black, 46\", type any}, {\"HL Mountain Frame - Black, 38\", type any}, {\"HL Mountain Frame - Silver, 38\", type any}, {\"Road-150 Red, 62\", type any}, {\"Road-150 Red, 44\", type any}, {\"Road-150 Red, 48\", type any}, {\"Road-150 Red, 52\", type any}, {\"Road-150 Red, 56\", type any}, {\"Road-450 Red, 58\", type any}, {\"Road-450 Red, 60\", type any}, {\"Road-450 Red, 44\", type any}, {\"Road-450 Red, 48\", type any}, {\"Road-450 Red, 52\", type any}, {\"Road-650 Red, 58\", type any}, {\"Road-650 Red, 60\", type any}, {\"Road-650 Red, 62\", type any}, {\"Road-650 Red, 44\", type any}, {\"Road-650 Red, 48\", type any}, {\"Road-650 Red, 52\", type any}, {\"Road-650 Black, 58\", type any}, {\"Road-650 Black, 60\", type any}, {\"Road-650 Black, 62\", type any}, {\"Road-650 Black, 44\", type any}, {\"Road-650 Black, 48\", type any}, {\"Road-650 Black, 52\", type any}, {\"Mountain-100 Silver, 38\", type any}, {\"Mountain-100 Silver, 42\", type any}, {\"Mountain-100 Silver, 44\", type any}, {\"Mountain-100 Silver, 48\", type any}, {\"Mountain-100 Black, 38\", type any}, {\"Mountain-100 Black, 42\", type any}, {\"Mountain-100 Black, 44\", type any}, {\"Mountain-100 Black, 48\", type any}, {\"Mountain-200 Silver, 38\", type any}, {\"Mountain-200 Silver, 42\", type any}, {\"Mountain-200 Silver, 46\", type any}, {\"Mountain-200 Black, 38\", type any}, {\"Mountain-200 Black, 42\", type any}, {\"Mountain-200 Black, 46\", type any}, {\"Mountain-300 Black, 38\", type any}, {\"Mountain-300 Black, 40\", type any}, {\"Mountain-300 Black, 44\", type any}, {\"Mountain-300 Black, 48\", type any}, {\"Road-250 Red, 44\", type any}, {\"Road-250 Red, 48\", type any}, {\"Road-250 Red, 52\", type any}, {\"Road-250 Red, 58\", type any}, {\"Road-250 Black, 44\", type any}, {\"Road-250 Black, 48\", type any}, {\"Road-250 Black, 52\", type any}, {\"Road-250 Black, 58\", type any}, {\"Road-550-W Yellow, 38\", type any}, {\"Road-550-W Yellow, 40\", type any}, {\"Road-550-W Yellow, 42\", type any}, {\"Road-550-W Yellow, 44\", type any}, {\"Road-550-W Yellow, 48\", type any}, {\"LL Fork\", type any}, {\"ML Fork\", type any}, {\"HL Fork\", type any}, {\"LL Headset\", type any}, {\"ML Headset\", type any}, {\"HL Headset\", type any}, {\"LL Mountain Handlebars\", type any}, {\"ML Mountain Handlebars\", type any}, {\"HL Mountain Handlebars\", type any}, {\"LL Road Handlebars\", type any}, {\"ML Road Handlebars\", type any}, {\"HL Road Handlebars\", type any}, {\"ML Mountain Frame - Black, 38\", type any}, {\"LL Mountain Front Wheel\", type any}, {\"ML Mountain Front Wheel\", type any}, {\"HL Mountain Front Wheel\", type any}, {\"LL Road Front Wheel\", type any}, {\"ML Road Front Wheel\", type any}, {\"HL Road Front Wheel\", type any}, {\"Touring Front Wheel\", type any}, {\"ML Road Frame-W - Yellow, 38\", type any}, {\"LL Mountain Rear Wheel\", type any}, {\"ML Mountain Rear Wheel\", type any}, {\"HL Mountain Rear Wheel\", type any}, {\"LL Road Rear Wheel\", type any}, {\"ML Road Rear Wheel\", type any}, {\"HL Road Rear Wheel\", type any}, {\"Touring Rear Wheel\", type any}, {\"ML Mountain Frame - Black, 40\", type any}, {\"ML Mountain Frame - Black, 44\", type any}, {\"ML Mountain Frame - Black, 48\", type any}, {\"ML Road Frame-W - Yellow, 40\", type any}, {\"ML Road Frame-W - Yellow, 42\", type any}, {\"ML Road Frame-W - Yellow, 44\", type any}, {\"ML Road Frame-W - Yellow, 48\", type any}, {\"HL Road Frame - Black, 62\", type any}, {\"HL Road Frame - Black, 44\", type any}, {\"HL Road Frame - Black, 48\", type any}, {\"HL Road Frame - Black, 52\", type any}, {\"Men's Sports Shorts, S\", type any}, {\"Touring-Panniers, Large\", type any}, {\"Cable Lock\", type any}, {\"Minipump\", type any}, {\"Mountain Pump\", type any}, {\"Taillights - Battery-Powered\", type any}, {\"Headlights - Dual-Beam\", type any}, {\"Headlights - Weatherproof\", type any}, {\"Men's Sports Shorts, M\", type any}, {\"Men's Sports Shorts, L\", type any}, {\"Men's Sports Shorts, XL\", type any}, {\"Women's Tights, S\", type any}, {\"Women's Tights, M\", type any}}),",
          "    #\"Demoted Headers\" = Table.DemoteHeaders(#\"Changed Type\"),",
          "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Demoted Headers\",{{\"Column1\", type text}, {\"Column2\", type any}, {\"Column3\", type any}, {\"Column4\", type any}, {\"Column5\", type any}, {\"Column6\", type any}, {\"Column7\", type any}, {\"Column8\", type any}, {\"Column9\", type any}, {\"Column10\", type any}, {\"Column11\", type any}, {\"Column12\", type any}, {\"Column13\", type any}, {\"Column14\", type any}, {\"Column15\", type any}, {\"Column16\", type any}, {\"Column17\", type any}, {\"Column18\", type any}, {\"Column19\", type any}, {\"Column20\", type any}, {\"Column21\", type any}, {\"Column22\", type any}, {\"Column23\", type any}, {\"Column24\", type any}, {\"Column25\", type any}, {\"Column26\", type any}, {\"Column27\", type any}, {\"Column28\", type any}, {\"Column29\", type any}, {\"Column30\", type any}, {\"Column31\", type any}, {\"Column32\", type any}, {\"Column33\", type any}, {\"Column34\", type any}, {\"Column35\", type any}, {\"Column36\", type any}, {\"Column37\", type any}, {\"Column38\", type any}, {\"Column39\", type any}, {\"Column40\", type any}, {\"Column41\", type any}, {\"Column42\", type any}, {\"Column43\", type any}, {\"Column44\", type any}, {\"Column45\", type any}, {\"Column46\", type any}, {\"Column47\", type any}, {\"Column48\", type any}, {\"Column49\", type any}, {\"Column50\", type any}, {\"Column51\", type any}, {\"Column52\", type any}, {\"Column53\", type any}, {\"Column54\", type any}, {\"Column55\", type any}, {\"Column56\", type any}, {\"Column57\", type any}, {\"Column58\", type any}, {\"Column59\", type any}, {\"Column60\", type any}, {\"Column61\", type any}, {\"Column62\", type any}, {\"Column63\", type any}, {\"Column64\", type any}, {\"Column65\", type any}, {\"Column66\", type any}, {\"Column67\", type any}, {\"Column68\", type any}, {\"Column69\", type any}, {\"Column70\", type any}, {\"Column71\", type any}, {\"Column72\", type any}, {\"Column73\", type any}, {\"Column74\", type any}, {\"Column75\", type any}, {\"Column76\", type any}, {\"Column77\", type any}, {\"Column78\", type any}, {\"Column79\", type any}, {\"Column80\", type any}, {\"Column81\", type any}, {\"Column82\", type any}, {\"Column83\", type any}, {\"Column84\", type any}, {\"Column85\", type any}, {\"Column86\", type any}, {\"Column87\", type any}, {\"Column88\", type any}, {\"Column89\", type any}, {\"Column90\", type any}, {\"Column91\", type any}, {\"Column92\", type any}, {\"Column93\", type any}, {\"Column94\", type any}, {\"Column95\", type any}, {\"Column96\", type any}, {\"Column97\", type any}, {\"Column98\", type any}, {\"Column99\", type any}, {\"Column100\", type any}, {\"Column101\", type any}, {\"Column102\", type any}, {\"Column103\", type any}, {\"Column104\", type any}, {\"Column105\", type any}, {\"Column106\", type any}, {\"Column107\", type any}, {\"Column108\", type any}, {\"Column109\", type any}, {\"Column110\", type any}, {\"Column111\", type any}, {\"Column112\", type any}, {\"Column113\", type any}, {\"Column114\", type any}, {\"Column115\", type any}, {\"Column116\", type any}, {\"Column117\", type any}, {\"Column118\", type any}, {\"Column119\", type any}, {\"Column120\", type any}, {\"Column121\", type any}, {\"Column122\", type any}, {\"Column123\", type any}, {\"Column124\", type any}, {\"Column125\", type any}, {\"Column126\", type any}, {\"Column127\", type any}, {\"Column128\", type any}, {\"Column129\", type any}, {\"Column130\", type any}, {\"Column131\", type any}, {\"Column132\", type any}, {\"Column133\", type any}, {\"Column134\", type any}, {\"Column135\", type any}, {\"Column136\", type any}, {\"Column137\", type any}, {\"Column138\", type any}, {\"Column139\", type any}, {\"Column140\", type any}, {\"Column141\", type any}, {\"Column142\", type any}, {\"Column143\", type any}, {\"Column144\", type any}, {\"Column145\", type any}, {\"Column146\", type any}, {\"Column147\", type any}, {\"Column148\", type any}, {\"Column149\", type any}, {\"Column150\", type any}}),",
          "    #\"Transposed Table\" = Table.Transpose(#\"Changed Type1\"),",
          "    #\"Promoted Headers1\" = Table.PromoteHeaders(#\"Transposed Table\", [PromoteAllScalars=true]),",
          "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Promoted Headers1\",{{\"Product Name\", type text}, {\"ProductCategory\", type text}, {\"Sales\", type number}, {\"UnitPrice\", type number}})",
          "in",
          "    #\"Changed Type2\""
        ],
        "kind": "m",
        "lineageTag": "e3407c1c-9d97-4651-8440-1cfa0d9a2d74"
      },
      {
        "name": "Table",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45W8nD1DFbSUTI0ABLGRkAipThNKVYnWskrsbI4Pw8oYASSMjKGSBWD5bwzc3JKE2FyxkYQfWDZWAA=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t, #\"Jan-2022\" = _t, #\"Feb-2022\" = _t, #\"MAr-2022\" = _t]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}, {\"Jan-2022\", Int64.Type}, {\"Feb-2022\", Int64.Type}, {\"MAr-2022\", type text}}),",
          "    #\"Unpivoted Other Columns\" = Table.UnpivotOtherColumns(#\"Changed Type\", {\"Column1\"}, \"Attribute\", \"Value\"),",
          "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Unpivoted Other Columns\",{{\"Attribute\", type date}})",
          "in",
          "    #\"Changed Type1\""
        ],
        "kind": "m",
        "lineageTag": "d7310b14-83f3-47bb-bf65-b586aa9f299f"
      }
    ],
    "relationships": [
      {
        "name": "AutoDetected_430c0083-71a7-4749-b04d-94e6937fc32c",
        "fromColumn": "customerID",
        "fromTable": "Fact table",
        "toColumn": "customerID",
        "toTable": "DimCustomer"
      },
      {
        "name": "AutoDetected_e639bd9a-5d76-41df-8daf-d5adff2b4e29",
        "fromColumn": "employeeID",
        "fromTable": "Fact table",
        "toColumn": "employeeID",
        "toTable": "DimEmployee"
      },
      {
        "name": "AutoDetected_4d461760-87de-44c9-887f-1bd6a02e7eaf",
        "fromColumn": "productID",
        "fromTable": "Fact table",
        "toColumn": "productID",
        "toTable": "DimProduct"
      },
      {
        "name": "AutoDetected_bbe6ef3c-ad1e-42a7-9b66-86cdb908df9f",
        "fromColumn": "supplierID",
        "fromTable": "Fact table",
        "toColumn": "supplierID",
        "toTable": "DimSupplier"
      },
      {
        "name": "cc92247b-c06e-abe6-f820-c9c420ad3186",
        "fromColumn": "orderDate",
        "fromTable": "Fact table",
        "toColumn": "Date",
        "toTable": "AutoCal"
      }
    ],
    "roles": [
      {
        "name": "Supplier 10",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "c0425d9732db420d9f27cd4be59ff226"
          }
        ],
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "Fact table",
            "filterExpression": "[supplierID] == 10"
          }
        ]
      },
      {
        "name": "Supplier 5",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "5855f7e028944418808438182070faed"
          }
        ],
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "Fact table",
            "filterExpression": "[supplierID] == 5"
          }
        ]
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Fact table",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "orderID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "542c5f58-3867-4bfd-b226-fedad6f6bfd5",
            "sourceColumn": "orderID",
            "summarizeBy": "count"
          },
          {
            "name": "customerID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "460494cd-a8ee-4c39-bc92-eb534c781930",
            "sourceColumn": "customerID",
            "summarizeBy": "none"
          },
          {
            "name": "employeeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f9ea569f-6b96-4bc0-b6b6-ce241e52a6a4",
            "sourceColumn": "employeeID",
            "summarizeBy": "none"
          },
          {
            "name": "orderDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "fa466e07-6fe4-4bb1-8451-96c6c7775296",
            "sourceColumn": "orderDate",
            "summarizeBy": "none"
          },
          {
            "name": "requiredDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "6c1a7bf4-8647-42c5-a2db-bc86aba681e4",
            "sourceColumn": "requiredDate",
            "summarizeBy": "none"
          },
          {
            "name": "shippedDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "5c6ef66b-a700-41e6-b061-789f0fe83141",
            "sourceColumn": "shippedDate",
            "summarizeBy": "none"
          },
          {
            "name": "shipVia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b5c50c80-8979-4ce0-bc36-4f805a542c60",
            "sourceColumn": "shipVia",
            "summarizeBy": "sum"
          },
          {
            "name": "Freight",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a29d4d62-fe1e-4b85-a399-373cabb2d953",
            "sourceColumn": "Freight",
            "summarizeBy": "sum"
          },
          {
            "name": "productID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cbfcea21-411e-4329-ac6b-52c24dd9c486",
            "sourceColumn": "productID",
            "summarizeBy": "none"
          },
          {
            "name": "unitPrice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "63877c83-b571-47f6-8ec5-fe3f7a699355",
            "sourceColumn": "unitPrice",
            "summarizeBy": "sum"
          },
          {
            "name": "quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "014895e1-e594-49c8-8d5c-99f41b67f18e",
            "sourceColumn": "quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "discount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e94a05aa-2811-4e44-ac4f-8f9be2b64b8b",
            "sourceColumn": "discount",
            "summarizeBy": "sum"
          },
          {
            "name": "supplierID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "da83fd80-a189-4719-8670-0aa5ccae9682",
            "sourceColumn": "supplierID",
            "summarizeBy": "none"
          },
          {
            "name": "categoryID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "241c189f-35ab-412e-b617-1dbcdd97828c",
            "sourceColumn": "categoryID",
            "summarizeBy": "count"
          },
          {
            "name": "unitPrice.1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "3052156d-11a3-4546-9254-acc55549186b",
            "sourceColumn": "unitPrice.1",
            "summarizeBy": "sum"
          },
          {
            "name": "unitsInStock",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2f388502-3e7f-4ce5-b1b9-0e8635be44db",
            "sourceColumn": "unitsInStock",
            "summarizeBy": "sum"
          },
          {
            "name": "unitsOnOrder",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6611a5be-f9fa-4838-80de-a5dc0d825ac0",
            "sourceColumn": "unitsOnOrder",
            "summarizeBy": "sum"
          },
          {
            "name": "reorderLevel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "11bd68af-53f8-408a-ac76-46ca34e93d8a",
            "sourceColumn": "reorderLevel",
            "summarizeBy": "sum"
          },
          {
            "name": "discontinued",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "841800b2-6a46-4495-9c19-ae1dfaf598ef",
            "sourceColumn": "discontinued",
            "summarizeBy": "sum"
          },
          {
            "name": "Gross Sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "'Fact table'[unitPrice]*'Fact table'[quantity]",
            "isDataTypeInferred": true,
            "lineageTag": "8f5fbc72-bd78-4eec-87f3-5a3f2d6b1cc3",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Net Sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "'Fact table'[Gross Sales]*(1-'Fact table'[discount])",
            "isDataTypeInferred": true,
            "lineageTag": "1a1de46c-4b9b-4995-a079-91b3b1b0a960",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "f35f3b2c-7d6d-4cdb-b74a-cb1f3751f447",
        "measures": [
          {
            "name": "Gross Revenue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM('Fact table'[Gross Sales])",
            "lineageTag": "cd14402c-ea2f-450a-b843-a67a548c18ef"
          }
        ],
        "partitions": [
          {
            "name": "Fact table",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Sodiq\\Documents\\Self Dev\\Data_Preprocessing_&_Modelling.xlsx\"), null, true),",
                "    #\"Data Modelling_Sheet\" = Source{[Item=\"Data Modelling\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Data Modelling_Sheet\", [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"orderID\", Int64.Type}, {\"customerID\", type text}, {\"employeeID\", Int64.Type}, {\"orderDate\", type date}, {\"requiredDate\", type date}, {\"shippedDate\", type date}, {\"shipVia\", Int64.Type}, {\"Freight\", type number}, {\"productID\", Int64.Type}, {\"unitPrice\", type number}, {\"quantity\", Int64.Type}, {\"discount\", type number}, {\"companyName\", type text}, {\"contactName\", type text}, {\"contactTitle\", type text}, {\"employees.lastName\", type text}, {\"employees.firstName\", type text}, {\"employees.title\", type text}, {\"productName\", type text}, {\"supplierID\", Int64.Type}, {\"categoryID\", Int64.Type}, {\"quantityPerUnit\", type text}, {\"unitPrice.1\", type number}, {\"unitsInStock\", Int64.Type}, {\"unitsOnOrder\", Int64.Type}, {\"reorderLevel\", Int64.Type}, {\"discontinued\", Int64.Type}, {\"categoryName\", type text}, {\"suppliers.companyName\", type text}, {\"suppliers.contactName\", type text}, {\"suppliers.contactTitle\", type text}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Changed Type\",{\"orderID\", \"customerID\", \"employeeID\", \"orderDate\", \"requiredDate\", \"shippedDate\", \"shipVia\", \"Freight\", \"productID\", \"unitPrice\", \"quantity\", \"discount\", \"supplierID\", \"categoryID\", \"unitPrice.1\", \"unitsInStock\", \"unitsOnOrder\", \"reorderLevel\", \"discontinued\"})",
                "in",
                "    #\"Removed Other Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DimCustomer",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "customerID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6682afa5-73f7-4d28-a896-6ebaf9813a41",
            "sourceColumn": "customerID",
            "summarizeBy": "none"
          },
          {
            "name": "companyName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0d5c636c-a6ee-4a17-a921-7fae00914945",
            "sourceColumn": "companyName",
            "summarizeBy": "none"
          },
          {
            "name": "contactName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "01127686-17ba-4a9d-9c6a-54f406f3867a",
            "sourceColumn": "contactName",
            "summarizeBy": "none"
          },
          {
            "name": "contactTitle",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "30b3af16-d30f-416b-9aee-886e28a9b57c",
            "sourceColumn": "contactTitle",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "b6307631-f6f7-485b-ba75-423404aca68d",
        "partitions": [
          {
            "name": "DimCustomer",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Sodiq\\Documents\\Self Dev\\Data_Preprocessing_&_Modelling.xlsx\"), null, true),",
                "    #\"Data Modelling_Sheet\" = Source{[Item=\"Data Modelling\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Data Modelling_Sheet\", [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"orderID\", Int64.Type}, {\"customerID\", type text}, {\"employeeID\", Int64.Type}, {\"orderDate\", type date}, {\"requiredDate\", type date}, {\"shippedDate\", type date}, {\"shipVia\", Int64.Type}, {\"Freight\", type number}, {\"productID\", Int64.Type}, {\"unitPrice\", type number}, {\"quantity\", Int64.Type}, {\"discount\", type number}, {\"companyName\", type text}, {\"contactName\", type text}, {\"contactTitle\", type text}, {\"employees.lastName\", type text}, {\"employees.firstName\", type text}, {\"employees.title\", type text}, {\"productName\", type text}, {\"supplierID\", Int64.Type}, {\"categoryID\", Int64.Type}, {\"quantityPerUnit\", type text}, {\"unitPrice.1\", type number}, {\"unitsInStock\", Int64.Type}, {\"unitsOnOrder\", Int64.Type}, {\"reorderLevel\", Int64.Type}, {\"discontinued\", Int64.Type}, {\"categoryName\", type text}, {\"suppliers.companyName\", type text}, {\"suppliers.contactName\", type text}, {\"suppliers.contactTitle\", type text}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Changed Type\",{\"customerID\", \"companyName\", \"contactName\", \"contactTitle\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\", {\"customerID\"})",
                "in",
                "    #\"Removed Duplicates\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DimEmployee",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "employeeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cb525119-0dc1-43c4-b965-2722935e7fd7",
            "sourceColumn": "employeeID",
            "summarizeBy": "none"
          },
          {
            "name": "employees.lastName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "603277c7-dd55-448f-8f38-f4e752d2fa27",
            "sourceColumn": "employees.lastName",
            "summarizeBy": "none"
          },
          {
            "name": "employees.firstName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "512e657d-37ad-4e3e-a8e2-baf8cf4a78bd",
            "sourceColumn": "employees.firstName",
            "summarizeBy": "none"
          },
          {
            "name": "employees.title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "28dde698-1602-48fc-9a7f-138ee70bf889",
            "sourceColumn": "employees.title",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "2db48281-76d0-4798-b6cb-2355d397ca25",
        "partitions": [
          {
            "name": "DimEmployee",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Sodiq\\Documents\\Self Dev\\Data_Preprocessing_&_Modelling.xlsx\"), null, true),",
                "    #\"Data Modelling_Sheet\" = Source{[Item=\"Data Modelling\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Data Modelling_Sheet\", [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"orderID\", Int64.Type}, {\"customerID\", type text}, {\"employeeID\", Int64.Type}, {\"orderDate\", type date}, {\"requiredDate\", type date}, {\"shippedDate\", type date}, {\"shipVia\", Int64.Type}, {\"Freight\", type number}, {\"productID\", Int64.Type}, {\"unitPrice\", type number}, {\"quantity\", Int64.Type}, {\"discount\", type number}, {\"companyName\", type text}, {\"contactName\", type text}, {\"contactTitle\", type text}, {\"employees.lastName\", type text}, {\"employees.firstName\", type text}, {\"employees.title\", type text}, {\"productName\", type text}, {\"supplierID\", Int64.Type}, {\"categoryID\", Int64.Type}, {\"quantityPerUnit\", type text}, {\"unitPrice.1\", type number}, {\"unitsInStock\", Int64.Type}, {\"unitsOnOrder\", Int64.Type}, {\"reorderLevel\", Int64.Type}, {\"discontinued\", Int64.Type}, {\"categoryName\", type text}, {\"suppliers.companyName\", type text}, {\"suppliers.contactName\", type text}, {\"suppliers.contactTitle\", type text}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Changed Type\",{\"employeeID\", \"employees.lastName\", \"employees.firstName\", \"employees.title\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\", {\"employeeID\"})",
                "in",
                "    #\"Removed Duplicates\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DimProduct",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "productID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "24495f15-59ca-4a21-806e-e36095cd9a81",
            "sourceColumn": "productID",
            "summarizeBy": "none"
          },
          {
            "name": "productName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0d97904a-935b-461b-9cc6-763a55a87708",
            "sourceColumn": "productName",
            "summarizeBy": "none"
          },
          {
            "name": "unitPrice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0b22379b-536e-42ac-a320-2f1213387fbe",
            "sourceColumn": "unitPrice",
            "summarizeBy": "none"
          },
          {
            "name": "quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a97bae69-43f4-490f-aba5-ed36c468a7a6",
            "sourceColumn": "quantity",
            "summarizeBy": "none"
          },
          {
            "name": "discount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e3b497eb-3f20-4f80-b739-c8ebe98b5f87",
            "sourceColumn": "discount",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "ffe0d5d3-ab30-47fb-a364-e6be9e010464",
        "partitions": [
          {
            "name": "DimProduct",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Sodiq\\Documents\\Self Dev\\Data_Preprocessing_&_Modelling.xlsx\"), null, true),",
                "    #\"Data Modelling_Sheet\" = Source{[Item=\"Data Modelling\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Data Modelling_Sheet\", [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"orderID\", Int64.Type}, {\"customerID\", type text}, {\"employeeID\", Int64.Type}, {\"orderDate\", type date}, {\"requiredDate\", type date}, {\"shippedDate\", type date}, {\"shipVia\", Int64.Type}, {\"Freight\", type number}, {\"productID\", Int64.Type}, {\"unitPrice\", type number}, {\"quantity\", Int64.Type}, {\"discount\", type number}, {\"companyName\", type text}, {\"contactName\", type text}, {\"contactTitle\", type text}, {\"employees.lastName\", type text}, {\"employees.firstName\", type text}, {\"employees.title\", type text}, {\"productName\", type text}, {\"supplierID\", Int64.Type}, {\"categoryID\", Int64.Type}, {\"quantityPerUnit\", type text}, {\"unitPrice.1\", type number}, {\"unitsInStock\", Int64.Type}, {\"unitsOnOrder\", Int64.Type}, {\"reorderLevel\", Int64.Type}, {\"discontinued\", Int64.Type}, {\"categoryName\", type text}, {\"suppliers.companyName\", type text}, {\"suppliers.contactName\", type text}, {\"suppliers.contactTitle\", type text}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Changed Type\",{\"productID\", \"unitPrice\", \"quantity\", \"discount\", \"productName\"}),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Removed Other Columns\",{\"productID\", \"productName\", \"unitPrice\", \"quantity\", \"discount\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Reordered Columns\", {\"productID\"})",
                "in",
                "    #\"Removed Duplicates\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DimSupplier",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "supplierID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7963dfa3-9dd6-479a-b256-db5b54f76eab",
            "sourceColumn": "supplierID",
            "summarizeBy": "none"
          },
          {
            "name": "suppliers.companyName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3850442b-52af-459b-bf13-bea49144a900",
            "sourceColumn": "suppliers.companyName",
            "summarizeBy": "none"
          },
          {
            "name": "suppliers.contactName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "64e77818-71f5-4444-a819-f6a8baf30987",
            "sourceColumn": "suppliers.contactName",
            "summarizeBy": "none"
          },
          {
            "name": "suppliers.contactTitle",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ae57c873-471a-439d-8362-f2acb0e0cad5",
            "sourceColumn": "suppliers.contactTitle",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "90a2b9f6-6bcc-41d0-81b0-a36e7adf02f1",
        "partitions": [
          {
            "name": "DimSupplier",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Sodiq\\Documents\\Self Dev\\Data_Preprocessing_&_Modelling.xlsx\"), null, true),",
                "    #\"Data Modelling_Sheet\" = Source{[Item=\"Data Modelling\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Data Modelling_Sheet\", [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"orderID\", Int64.Type}, {\"customerID\", type text}, {\"employeeID\", Int64.Type}, {\"orderDate\", type date}, {\"requiredDate\", type date}, {\"shippedDate\", type date}, {\"shipVia\", Int64.Type}, {\"Freight\", type number}, {\"productID\", Int64.Type}, {\"unitPrice\", type number}, {\"quantity\", Int64.Type}, {\"discount\", type number}, {\"companyName\", type text}, {\"contactName\", type text}, {\"contactTitle\", type text}, {\"employees.lastName\", type text}, {\"employees.firstName\", type text}, {\"employees.title\", type text}, {\"productName\", type text}, {\"supplierID\", Int64.Type}, {\"categoryID\", Int64.Type}, {\"quantityPerUnit\", type text}, {\"unitPrice.1\", type number}, {\"unitsInStock\", Int64.Type}, {\"unitsOnOrder\", Int64.Type}, {\"reorderLevel\", Int64.Type}, {\"discontinued\", Int64.Type}, {\"categoryName\", type text}, {\"suppliers.companyName\", type text}, {\"suppliers.contactName\", type text}, {\"suppliers.contactTitle\", type text}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Changed Type\",{\"supplierID\", \"suppliers.companyName\", \"suppliers.contactName\", \"suppliers.contactTitle\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\", {\"supplierID\"})",
                "in",
                "    #\"Removed Duplicates\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Supplier10",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "663d6f4087fe4ed6bb5a7b4f22e0db8f"
          }
        ],
        "columns": [
          {
            "name": "orderID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "4ee1a356-6ebc-4235-95f1-788e78804b29",
            "sourceColumn": "Fact table[orderID]",
            "summarizeBy": "count",
            "type": "calculatedTableColumn"
          },
          {
            "name": "customerID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "fa397e8b-fc17-418f-b516-fb435c88439a",
            "sourceColumn": "Fact table[customerID]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "employeeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "4796c634-e1d4-44f0-bfaa-beef43d7fd16",
            "sourceColumn": "Fact table[employeeID]",
            "summarizeBy": "count",
            "type": "calculatedTableColumn"
          },
          {
            "name": "orderDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "050526ee-1425-4839-a364-0b87f2dabbdb",
            "sourceColumn": "Fact table[orderDate]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "requiredDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "85c83a53-f532-44c5-bb87-e342f382fbbf",
            "sourceColumn": "Fact table[requiredDate]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "shippedDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "17d44b07-362b-4dc8-b563-5fdf6437daac",
            "sourceColumn": "Fact table[shippedDate]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "shipVia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "87a96357-0237-47f1-a951-a857d87129dc",
            "sourceColumn": "Fact table[shipVia]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Freight",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "709bf77c-10fc-4a87-bc14-730fa1e655c7",
            "sourceColumn": "Fact table[Freight]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "productID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "33cdf935-d192-4567-9af7-ed42626c1951",
            "sourceColumn": "Fact table[productID]",
            "summarizeBy": "count",
            "type": "calculatedTableColumn"
          },
          {
            "name": "unitPrice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "90ff5fb6-0931-445f-bdc8-8e9095f90a08",
            "sourceColumn": "Fact table[unitPrice]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "5435bdb0-3c0e-4b66-a3c7-06023afc3873",
            "sourceColumn": "Fact table[quantity]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "discount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "c0c86c17-e9f6-495f-b6f5-8a94e2b6512d",
            "sourceColumn": "Fact table[discount]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "supplierID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "e967fce3-8e7c-49d9-94c5-4e9fa83dbd84",
            "sourceColumn": "Fact table[supplierID]",
            "summarizeBy": "count",
            "type": "calculatedTableColumn"
          },
          {
            "name": "categoryID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "6a082cf5-6d68-48ad-98bc-c5237da29c8b",
            "sourceColumn": "Fact table[categoryID]",
            "summarizeBy": "count",
            "type": "calculatedTableColumn"
          },
          {
            "name": "unitPrice.1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "7cd70ed0-150f-45d7-ab5a-ca1757cab7cc",
            "sourceColumn": "Fact table[unitPrice.1]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "unitsInStock",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "5e55cd2c-7dd9-4d4c-b7d2-85dc618478d1",
            "sourceColumn": "Fact table[unitsInStock]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "unitsOnOrder",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "d6c26950-89cb-477a-a65c-6b7b37ba8641",
            "sourceColumn": "Fact table[unitsOnOrder]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "reorderLevel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "6a0b5a17-17c6-4617-afde-1924e8208169",
            "sourceColumn": "Fact table[reorderLevel]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "discontinued",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "9e344297-569b-465d-b80e-a37937090d2a",
            "sourceColumn": "Fact table[discontinued]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Gross Sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "d6ce89fe-74b2-4fa0-ab5f-4ba6654960ad",
            "sourceColumn": "Fact table[Gross Sales]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Net Sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "a93cbf6e-f969-426e-a4f7-f82b4b0a673e",
            "sourceColumn": "Fact table[Net Sales]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "bd25f574-8065-4f27-ac05-8b7145008830",
        "partitions": [
          {
            "name": "Supplier10",
            "mode": "import",
            "source": {
              "expression": "FILTER('Fact table','Fact table'[supplierID]=10)",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Calendar",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "f96b983ce3534a97895c236edfc20591"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "5889bb82-e87b-4ba0-8173-1ca6b31138b6",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "88448618-f4e4-4a2a-8dfd-871831f78000",
        "partitions": [
          {
            "name": "Calendar",
            "mode": "import",
            "source": {
              "expression": "CALENDAR(\"1/1/2020\",\"12/31/2025\")",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "AutoCal",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "e9e44672d51d44ad9ebde772bd687582"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isDataTypeInferred": true,
            "isKey": true,
            "isNameInferred": true,
            "lineageTag": "56edcf07-1284-48b6-9723-4358375a0b18",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT(AutoCal[Date],\"yyyy\")",
            "isDataTypeInferred": true,
            "lineageTag": "c5b194a6-0cfb-4a0b-886c-4434925c4ecf",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT(AutoCal[Date],\"mmmm\")",
            "isDataTypeInferred": true,
            "lineageTag": "bf254beb-a980-48c1-aed9-2c538f5608d3",
            "sortByColumn": "MonthNumber",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "FORMAT(AutoCal[Date],\"m\")",
            "formatString": "0",
            "lineageTag": "6c165605-2fb9-4c9b-9fc3-192759d769a4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT(AutoCal[Date],\"d\")",
            "isDataTypeInferred": true,
            "lineageTag": "17cd2beb-0fc2-4c7a-83f0-5c82aaeb12a3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "DayofWeek",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT(AutoCal[Date],\"dddd\")",
            "isDataTypeInferred": true,
            "lineageTag": "a5a385bd-c826-4b3c-9921-78b497d098c6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quater",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "\"Q\"&FORMAT(AutoCal[Date],\"Q\")",
            "isDataTypeInferred": true,
            "lineageTag": "d937a372-72ba-43c6-b2af-89840a69f24d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "WEEKNUM(AutoCal[Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "384790d8-8b41-4673-92b6-efd7c6c68158",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "dataCategory": "Time",
        "lineageTag": "7ccba3af-4c82-4fa8-97c9-f81bd3999be5",
        "measures": [
          {
            "name": "Transaction",
            "expression": "COUNTROWS('Fact table')",
            "formatString": "0",
            "lineageTag": "343946f7-d452-473b-be1c-447d07b1b411"
          }
        ],
        "partitions": [
          {
            "name": "AutoCal",
            "mode": "import",
            "source": {
              "expression": "CALENDARAUTO()",
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}